export enum ClaimValidationReason {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_NOT_ACTIVE = "USER_NOT_ACTIVE",
  NO_ACTIVE_MERKLE_ROOT = "NO_ACTIVE_MERKLE_ROOT",
  PROOF_NOT_FOUND = "PROOF_NOT_FOUND",
  INVALID_ALLOCATION = "INVALID_ALLOCATION",
  INVALID_PROOF_DATA = "INVALID_PROOF_DATA",
  ALREADY_CLAIMED = "ALREADY_CLAIMED",
  INVALID_MERKLE_PROOF = "INVALID_MERKLE_PROOF",
}